# Generated by Django 4.2.7 on 2025-01-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_election_officer_register_rename_reg_register_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.IntegerField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='election_officer_register',
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
