# Generated by Django 4.2.7 on 2025-01-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_electionofficer_delete_election_officer_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionofficer',
            name='register_no',
            field=models.IntegerField(),
        ),
    ]
