# Generated by Django 4.2.7 on 2025-01-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_electionofficer_register_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionofficer',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
