# Generated by Django 4.2.7 on 2025-01-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_election_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='is_active',
            field=models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available')], max_length=20),
        ),
    ]
