# Generated by Django 4.2.7 on 2025-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_alter_election_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='created_by',
            field=models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available')], max_length=20),
        ),
    ]
