# Generated by Django 4.2.7 on 2025-01-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_alter_election_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='created_by',
        ),
    ]
