# Generated by Django 4.2.7 on 2025-01-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_remove_election_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='regno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
